services:
  ursim:
    image: universalrobots/ursim_polyscopex:10.9.0
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    network_mode: bridge