name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-install-and-test-urcap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3
      - name: Run Docker compose
        run: docker compose -f "docker-compose.yml" up -d --build
      - name: Wait for URService to be ready
        run: |
          echo "Waiting for service to report alive=true..."
          for i in {1..100}; do
            if curl -s http://localhost/universal-robots/urservice/api/v1/health | grep -q '"alive":\s*true'; then
              echo "✅ Service is alive"
              break
            fi
            echo "Waiting... ($i/100)"
            sleep 5
          done

      - name: Wait for PolyScope X services to be ready
        run: |
          echo "Waiting for service to report alive=true..."
          for i in {1..100}; do
            if curl -s http://localhost/universal-robots/polyscopex-services/polyscopex-services/rest-api/application/boot/progress | grep -q 'STARTED'; then
              echo "✅ Service is alive"
              break
            fi
            echo "Waiting... ($i/100)"
            sleep 5
          done
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure scoped registry and npm settings
        working-directory: my_urcap_id
        run: |
          npm config set @universal-robots:registry https://pkgs.dev.azure.com/polyscopex/api/_packaging/polyscopex/npm/registry/
          npm config set strict-ssl false
      - name: Install npm packages
        working-directory: my_urcap_id
        run: npm install
      - name: Build URCap
        working-directory: my_urcap_id
        run: npm run build
      - name: Install-urcap
        working-directory: my_urcap_id
        run: npm run install-urcap
      - name: Run Cypress tests in Docker
        run: |
          docker run --network host \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress/included:13.11.0

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos